apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-service
spec:
  type: ClusterIP
  selector:
    app: backend-k8s-deployment-label 
  ports:
    - port: 8000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-deployment
#  labels:
#    app: fastapi-k8s-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-k8s-deployment-label
  template:
    metadata:
      labels:
        app: backend-k8s-deployment-label
    spec:
      containers:
        - name: backend-application
          image: taxgptapplications.azurecr.io/tax-gpt-service:ingressupdated
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-backend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  # - host: taxgptapp.eastus.cloudapp.azure.com
  - http:
      paths:
      - path: /backend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-k8s-service
            port:
              number: 8000
