apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-service
spec:
  type: ClusterIP
  selector:
    app: frontend-k8s-deployment-label
  ports:
    - name: app-port
      port: 80
      targetPort: 80
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-deployment
#  labels:
#    app: fastapi-k8s-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-k8s-deployment-label
  template:
    metadata:
      labels:
        app: frontend-k8s-deployment-label
    spec:
      containers:
        - name: frontend-application
          image: taxgptapplications.azurecr.io/tax-gpt-ui:nofrontend
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
          - name: app-port
            containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  # - host: taxgptapp.eastus.cloudapp.azure.com
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend-k8s-service
            port:
              number: 80

